# Generated by Django 4.2.7 on 2024-02-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
