# Generated by Django 4.2.7 on 2024-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseUser', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Superuser'), (2, 'Client'), (3, 'Seller')]),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
